version: "3"

# https://github.com/pi-hole/docker-pi-hole/blob/master/README.md

services:
  pihole:
    container_name: "rsi"
    image: "pihole/pihole:latest"
    ports:
      - "53:53/tcp"
      - "53:53/udp"
      - "8080:80/tcp"
    environment:
      TZ: "America/New_York"
      WEBPASSWORD: "PasswordForSecondary"
      FTLCONF_LOCAL_IPV4: "192.168.1.12"
      FTLCONF_RATE_LIMIT: "1000/60"
      PIHOLE_DNS: "9.9.9.9;149.112.112.112;2620:fe::fe;2620:fe::9;1.1.1.1;1.0.0.1;2606:4700:4700::1111;2606:4700:4700::1001"
      DNSSEC: "true"
      TEMPERATUREUNIT: "f"
      WEBTHEME: "default-dark"
      DNSMASQ_LISTENING: "all"
    volumes:
      - "./etc-pihole:/etc/pihole"
      - "./etc-dnsmasq.d:/etc/dnsmasq.d"
    restart: "unless-stopped"
  orbital-sync:
    container_name: "osync"
    image: mattwebbio/orbital-sync:1
    environment:
      PRIMARY_HOST_BASE_URL: 'http://192.168.1.11'
      PRIMARY_HOST_PASSWORD: 'PasswordForPrimary'
      SECONDARY_HOST_1_BASE_URL: 'http://192.168.1.12:8080'
      SECONDARY_HOST_1_PASSWORD: 'PasswordForSecondary'
      INTERVAL_MINUTES: 60
      TZ: "America/New_York"
    restart: "unless-stopped"
